[package]
name = "engine"
description = "A small 2D game engine framework, written from scratch for learning."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
bytemuck.workspace = true
ecs.workspace = true
log.workspace = true
pollster.workspace = true
thiserror.workspace = true
wgpu.workspace = true
winit.workspace = true

[dev-dependencies]
env_logger.workspace = true

[lints]
workspace = true
